name: basiel
description: A Very Good Project created by Very Good CLI.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - apps/matties_app
  - packages/basiel_core
  - packages/basiel_supabase

dev_dependencies:
  melos: ^7.3.0

melos:
  scripts:
    build:
      run: flutter pub run build_runner build

    app:dev:
      run: |
        cd apps/matties_app
        flutter run --target lib/main_development.dart < /dev/tty
