name: matties_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=3.38.0"

resolution: workspace

dependencies:
  bloc: ^9.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_form_builder: ^10.2.0
  flutter_localizations:
    sdk: flutter
  form_builder_validators: ^11.0.0
  go_router: ^17.0.1
  intl: ^0.20.0
  slang: ^4.4.1
  slang_flutter: ^4.4.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  go_router_builder: ^4.1.3
  mocktail: ^1.0.4
  slang_build_runner: ^4.4.2
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
